import * as React from "react"

interface AlertTemplateProps {
  supplierName: string
  alertType: string
  severity: string
  vvsBefore?: number
  vvsAfter?: number
  description: string
  dashboardUrl: string
}

/**
 * React Email template for compliance alert notifications.
 */
export function AlertTemplate({
  supplierName,
  alertType,
  severity,
  vvsBefore,
  vvsAfter,
  description,
  dashboardUrl,
}: AlertTemplateProps) {
  const severityColors: Record<string, string> = {
    CRITICAL: "#EF4444",
    HIGH: "#F97316",
    MEDIUM: "#F59E0B",
    LOW: "#3B82F6",
    INFO: "#10B981",
  }

  const color = severityColors[severity] ?? "#8B9BB4"

  return (
    <html>
      <body style={{ fontFamily: "system-ui, sans-serif", backgroundColor: "#080A0F", color: "#E8EDF5", padding: "24px" }}>
        <div style={{ maxWidth: "600px", margin: "0 auto" }}>
          {/* Header */}
          <div style={{ marginBottom: "24px" }}>
            <h1 style={{ color: "#E8EDF5", fontSize: "24px", margin: "0 0 8px" }}>
              Meridian Alert
            </h1>
            <p style={{ color: "#8B9BB4", margin: 0 }}>
              Supply Chain ESG Compliance Intelligence
            </p>
          </div>

          {/* Alert card */}
          <div style={{
            backgroundColor: "#0E1117",
            border: `1px solid ${color}30`,
            borderRadius: "12px",
            padding: "20px",
            marginBottom: "20px",
          }}>
            <div style={{ display: "flex", alignItems: "center", gap: "12px", marginBottom: "16px" }}>
              <span style={{
                backgroundColor: `${color}15`,
                color,
                padding: "4px 10px",
                borderRadius: "20px",
                fontSize: "12px",
                fontWeight: "bold",
              }}>
                {severity}
              </span>
              <span style={{ color: "#8B9BB4", fontSize: "14px" }}>
                {alertType.replace(/_/g, " ").toUpperCase()}
              </span>
            </div>

            <h2 style={{ color: "#E8EDF5", fontSize: "18px", margin: "0 0 8px" }}>
              {supplierName}
            </h2>
            <p style={{ color: "#8B9BB4", fontSize: "14px", margin: "0 0 16px" }}>
              {description}
            </p>

            {vvsBefore !== undefined && vvsAfter !== undefined && (
              <div style={{
                backgroundColor: "#161B25",
                borderRadius: "8px",
                padding: "12px",
                display: "flex",
                gap: "24px",
              }}>
                <div>
                  <p style={{ color: "#4A5568", fontSize: "11px", margin: "0 0 4px" }}>VVS Before</p>
                  <p style={{ color: "#E8EDF5", fontSize: "20px", fontWeight: "bold", margin: 0 }}>
                    {vvsBefore.toFixed(0)}
                  </p>
                </div>
                <div>
                  <p style={{ color: "#4A5568", fontSize: "11px", margin: "0 0 4px" }}>VVS After</p>
                  <p style={{ color, fontSize: "20px", fontWeight: "bold", margin: 0 }}>
                    {vvsAfter.toFixed(0)}
                  </p>
                </div>
              </div>
            )}
          </div>

          {/* CTA */}
          <a
            href={dashboardUrl}
            style={{
              display: "inline-block",
              backgroundColor: "#3B82F6",
              color: "#FFFFFF",
              padding: "12px 24px",
              borderRadius: "8px",
              textDecoration: "none",
              fontWeight: "bold",
              fontSize: "14px",
            }}
          >
            View in Meridian Dashboard
          </a>

          {/* Footer */}
          <p style={{ color: "#4A5568", fontSize: "12px", marginTop: "24px" }}>
            This alert was generated by Meridian AI. To manage your notification preferences,
            visit Settings → Notifications.
          </p>
        </div>
      </body>
    </html>
  )
}
